jinx: Update to version 0.5.1

diff --git a/jinx b/jinx
--- a/jinx
+++ b/jinx
@@ -34,13 +34,14 @@ export LC_COLLATE
 umask 0022
 
 jinx_major_ver="0.5"
-jinx_minor_ver="0"
+jinx_minor_ver="1"
 
 jinx_version="${jinx_major_ver}.${jinx_minor_ver}"
 
 debian_snapshot="20250401T023134Z"
 
 XBPS_VERSION=0.59.2
+XBPS_B2SUM=cabe5676eb1611271f255c75f4439f3ef4ea6096d6fc26f0982da471556e1fd1733cb76a6d5857d3546513b157e8a3493624d09d989134f3f6d7763c55e98a83
 
 die() {
     echo "$1"
@@ -183,8 +184,6 @@ if ! [ -d "$(dirname "$JINX_CACHE_DIR")" ]; then
 fi
 make_dir "$JINX_CACHE_DIR"
 JINX_CACHE_DIR="$(cd "$JINX_CACHE_DIR" && pwd -P)"
-
-XBPS_BUILDENV="$JINX_CACHE_DIR/xbps_buildenv"
 
 if [ "$in_container" = "false" ]; then
     make_dir "${base_dir}/sources" "${build_dir}/host-builds" "${build_dir}/host-pkgs" "${build_dir}/builds" "${build_dir}/pkgs"
@@ -342,8 +341,9 @@ prepare_container() {
     sysroot_dir="${tmp}"
 
     for dep in $(cat "${deps_file}"); do
-        LD_LIBRARY_PATH="$XBPS_BUILDENV/usr/lib/$(uname -m)-linux-gnu" \
-            "${JINX_CACHE_DIR}"/xbps-bin/bin/xbps-install -y -r "${sysroot_dir}" -R "${build_dir}"/pkgs "${dep}" >/dev/null
+        XBPS_ARCH=invalid \
+        XBPS_TARGET_ARCH="${JINX_ARCH}" \
+            "$JINX_CACHE_DIR"/xbps-bin/xbps-install -y -r "${sysroot_dir}" -R "${build_dir}"/pkgs "${dep}" >/dev/null
     done
 
     if [ "$JINX_NATIVE_MODE" = "yes" ] && [ -z "$cross_compile" ]; then
@@ -861,7 +861,9 @@ do_package() {
     done
 
     cd "${build_dir}"/pkgs
-    "$JINX_CACHE_DIR"/xbps-bin/bin/xbps-create \
+        XBPS_ARCH=invalid \
+        XBPS_TARGET_ARCH="${JINX_ARCH}" \
+    "$JINX_CACHE_DIR"/xbps-bin/xbps-create \
         -A $JINX_ARCH \
         -s ${name} \
         -n ${name}-${version}_${revision} \
@@ -1039,9 +1041,9 @@ do_pkg() {
 
     destroy_container
 
-        LD_LIBRARY_PATH="$XBPS_BUILDENV/usr/lib/$(uname -m)-linux-gnu" \
-        XBPS_TARGET_ARCH=$JINX_ARCH \
-    "$JINX_CACHE_DIR"/xbps-bin/bin/xbps-rindex \
+        XBPS_ARCH=invalid \
+        XBPS_TARGET_ARCH="${JINX_ARCH}" \
+    "$JINX_CACHE_DIR"/xbps-bin/xbps-rindex \
         -a "${build_dir}"/pkgs/${name}-${version}_${revision}.${JINX_ARCH}.xbps \
         -f
 }
@@ -1195,8 +1197,9 @@ cmd_install() {
             die "* package '${name}' not built"
         fi
 
-        LD_LIBRARY_PATH="$XBPS_BUILDENV/usr/lib/$(uname -m)-linux-gnu" \
-            "$JINX_CACHE_DIR"/xbps-bin/bin/xbps-install -y -r "${sysroot}" -R "${build_dir}"/pkgs ${pkg} >/dev/null
+        XBPS_ARCH=invalid \
+        XBPS_TARGET_ARCH="${JINX_ARCH}" \
+            "$JINX_CACHE_DIR"/xbps-bin/xbps-install -y -r "${sysroot}" -R "${build_dir}"/pkgs ${pkg} >/dev/null
     done
 }
 
@@ -1888,15 +1891,29 @@ Acquire::Check-Valid-Until "0";' >> "$JINX_CACHE_DIR/sets/.image/etc/apt/apt.con
         chmod 755 "$f"
     done
 
-    run_in_container1 "$JINX_CACHE_DIR/sets/.image" apt-get install -y autopoint bash bison bzip2 curl diffutils docbook-xsl doxygen fakeroot file findutils flex gawk gettext grep gzip xsltproc libarchive13 libssl3t64 m4 make patch perl python3 sed tar texinfo w3m which xmlto xz-utils zlib1g zstd
+    run_in_container1 "$JINX_CACHE_DIR/sets/.image" apt-get install -y autopoint bash bison bzip2 curl diffutils docbook-xsl doxygen fakeroot file findutils flex gawk gettext grep gzip xsltproc m4 make patch perl python3 sed tar texinfo w3m which xmlto xz-utils zstd
 
     # Build xbps
+    XBPS_BUILDENV="$JINX_CACHE_DIR/xbps_buildenv"
     cp -Pprf "$JINX_CACHE_DIR/sets/.image/." "${XBPS_BUILDENV}/"
     curl -Lo "${XBPS_BUILDENV}/xbps-${XBPS_VERSION}.tar.gz" https://github.com/void-linux/xbps/archive/refs/tags/${XBPS_VERSION}.tar.gz
+    if ! "$JINX_CACHE_DIR/b2sum" "${XBPS_BUILDENV}/xbps-${XBPS_VERSION}.tar.gz" | grep "${XBPS_B2SUM}" >/dev/null 2>&1; then
+        die "Jinx: Failed to verify XBPS tarball"
+    fi
     ( cd "${XBPS_BUILDENV}" && gunzip < xbps-${XBPS_VERSION}.tar.gz | tar -xf - )
     run_in_container1 "${XBPS_BUILDENV}" apt-get install -y build-essential pkg-config zlib1g-dev libssl-dev libarchive-dev
-    run_in_container1 "${XBPS_BUILDENV}" sh -c "cd /xbps-${XBPS_VERSION} && CFLAGS='-O2 -pipe -Wno-error' ./configure --disable-debug --enable-rpath --prefix=/ --sysconfdir=/ && make -j${parallelism} && make DESTDIR=/xbps-bin install"
-    mv "${XBPS_BUILDENV}/xbps-bin" "$JINX_CACHE_DIR/"
+    # XXX: xbps upstream forgot to bump version string
+    run_in_container1 "${XBPS_BUILDENV}" sed -i 's/0\.59\.1/0.59.2/g' /xbps-${XBPS_VERSION}/configure
+    run_in_container1 "${XBPS_BUILDENV}" sed -i 's/&& DEBUG=yes/&& DEBUG=no/g' /xbps-${XBPS_VERSION}/configure
+    run_in_container1 "${XBPS_BUILDENV}" sh -c "cd /xbps-${XBPS_VERSION} && CFLAGS='-O2 -pipe -Wno-error' ./configure --verbose --enable-static --enable-rpath --prefix=/ --sysconfdir=/etc"
+    run_in_container1 "${XBPS_BUILDENV}" sed -i 's/-lxml2/-lxml2 -llzma -lm/g' /xbps-${XBPS_VERSION}/config.mk
+    run_in_container1 "${XBPS_BUILDENV}" sh -c "cd /xbps-${XBPS_VERSION} && make -j${parallelism} && make DESTDIR=/xbps-bin install"
+    for f in "${XBPS_BUILDENV}"/xbps-bin/bin/*.static; do
+        mv "$f" "${f%.static*}"
+    done
+    mv "${XBPS_BUILDENV}/xbps-bin/bin" "$JINX_CACHE_DIR/xbps-bin"
+    chmod -R 777 "${XBPS_BUILDENV}"
+    rm -rf "${XBPS_BUILDENV}"
 }
 
 first_use() {
@@ -1933,6 +1950,10 @@ fi
 
 if ! [ "$JINX_MAJOR_VER" = "$jinx_major_ver" ]; then
     die "$0: needed major version ($JINX_MAJOR_VER) differs from Jinx-provided major version ($jinx_major_ver)"
+fi
+
+if [ -z "$JINX_ARCH" ]; then
+    die "$0: required config variable \$JINX_ARCH missing"
 fi
 
 if ! [ -d "$JINX_CACHE_DIR" ]; then
